"""
Models for the Clappia API.
"""

from .workplace_user import WorkplaceUser
from .permissions import Permission
from .submission import (
    FilterCondition,
    SubmissionQuery,
    SubmissionQueryGroup,
    SubmissionFilters,
    AggregationOperand,
    AggregationDimension,
    AggregationMetric,
)
from .request import (
    CreateAppRequest,
    GetSubmissionsRequest,
    GetSubmissionsAggregationRequest,
    CreateSubmissionRequest,
    EditSubmissionRequest,
    UpdateSubmissionStatusRequest,
    UpdateSubmissionOwnersRequest,
    GetSubmissionsInExcelRequest,
    GetSubmissionsCountRequest,
    GetWorkflowRequest,
    AddWorkflowStepRequest,
    UpdateWorkflowStepRequest,
    ReorderWorkflowStepRequest,
    AddChartRequest,
    UpdateChartRequest,
    ReorderChartRequest,
    GetAppChartsRequest,
    AddUserToWorkplaceRequest,
    UpdateWorkplaceUserDetailsRequest,
    UpdateWorkplaceUserAttributesRequest,
    UpdateWorkplaceUserRoleRequest,
    UpdateWorkplaceUserGroupsRequest,
    AddUserToAppRequest,
    GetWorkplaceAppsRequest,
    GetWorkplaceUserAppsRequest,
    GetWorkplaceUsersRequest,

    ReorderSectionRequest,
    UpsertSectionRequest,

    AddPageBreakRequest,
    UpdatePageBreakRequest,

    UpsertFieldTextRequest,
    UpsertFieldTextAreaRequest,
    UpsertFieldDependencyAppRequest,
    UpsertFieldRestApiRequest,
    UpsertFieldAddressRequest,
    UpsertFieldDatabaseRequest,
    UpsertFieldDateRequest,
    UpsertFieldAIRequest,
    UpsertFieldCodeRequest,
    UpsertFieldCodeReaderRequest,
    UpsertFieldEmailInputRequest,
    UpsertFieldEmojiRequest,
    UpsertFieldFileRequest,
    UpsertFieldGpsLocationRequest,
    UpsertFieldLiveTrackingRequest,
    UpsertFieldManualAddressRequest,
    UpsertFieldPhoneNumberRequest,
    UpsertFieldProgressBarRequest,
    UpsertFieldSignatureRequest,
    UpsertFieldRangeRequest,
    UpsertFieldCounterRequest,
    UpsertFieldSliderRequest,
    UpsertFieldTimeRequest,
    UpsertFieldToggleRequest,
    UpsertFieldValidationRequest,
    UpsertFieldVideoViewerRequest,
    UpsertFieldVoiceRequest,
    UpsertFieldFormulaRequest,
    UpsertFieldImageViewerRequest,
    UpsertFieldRichTextEditorRequest,
    UpsertFieldNfcReaderRequest,
    UpsertFieldNumberInputRequest,
    UpsertFieldPdfViewerRequest,
    UpsertFieldReadOnlyFileRequest,
    UpsertFieldReadOnlyTextRequest,
    UpsertFieldTagsRequest,
    UpsertFieldUniqueSequentialRequest,
    UpsertFieldDropdownRequest,
    UpsertFieldRadioRequest,
    UpsertFieldUrlInputRequest,
    UpsertFieldCheckboxRequest,
    UpsertFieldRazorpayPaymentGatewayRequest,
    UpsertFieldEazypayPaymentGatewayRequest,
    UpsertFieldPaypalPaymentGatewayRequest,
    UpsertFieldStripePaymentGatewayRequest,
    UpsertFieldButtonRequest,
)
from .response import (
    BaseResponse,
    SubmissionResponse,
    SubmissionsAggregationResponse,
    SubmissionsResponse,
    SubmissionsExcelResponse,
    WorkflowResponse,
    WorkflowStepResponse,
    ChartResponse,
    GetAppChartsResponse,
    SubmissionsCountResponse,
    WorkplaceUserResponse,
    WorkplaceUserDetailsResponse,
    WorkplaceUserAttributesResponse,
    WorkplaceUserRoleResponse,
    WorkplaceUserGroupsResponse,
    AppUserResponse,
    WorkplaceAppResponse,
    WorkplaceUserAppsResponse,
    WorkplaceUsersResponse,

    AppDefinitionResponse,
    AppCreationResponse,

    FieldOperationResponse,
    PageBreakOperationResponse,

    UpsertSectionOperationResponse,
    ReorderSectionOperationResponse,
)

__all__ = [
    # ===== Core Models =====
    "WorkplaceUser",
    "Permission",

    # ===== Submission Models =====
    "FilterCondition",
    "SubmissionQuery",
    "SubmissionQueryGroup",
    "SubmissionFilters",
    "AggregationOperand",
    "AggregationDimension",
    "AggregationMetric",

    # ===== Request Models =====
    "CreateAppRequest",
    "GetSubmissionsRequest",
    "GetSubmissionsAggregationRequest",
    "CreateSubmissionRequest",
    "EditSubmissionRequest",
    "UpdateSubmissionStatusRequest",
    "UpdateSubmissionOwnersRequest",
    "GetSubmissionsInExcelRequest",
    "GetSubmissionsCountRequest",
    "GetWorkflowRequest",
    "AddWorkflowStepRequest",
    "UpdateWorkflowStepRequest",
    "ReorderWorkflowStepRequest",
    "AddChartRequest",
    "UpdateChartRequest",
    "ReorderChartRequest",
    "GetAppChartsRequest",

    "AddUserToWorkplaceRequest",
    "UpdateWorkplaceUserDetailsRequest",
    "UpdateWorkplaceUserAttributesRequest",
    "UpdateWorkplaceUserRoleRequest",
    "UpdateWorkplaceUserGroupsRequest",
    "AddUserToAppRequest",
    "GetWorkplaceAppsRequest",
    "GetWorkplaceUserAppsRequest",
    "GetWorkplaceUsersRequest",

    "ReorderSectionRequest",
    "UpsertSectionRequest",

    "AddPageBreakRequest",
    "UpdatePageBreakRequest",

    # Field Upserts
    "UpsertFieldTextRequest",
    "UpsertFieldTextAreaRequest",
    "UpsertFieldDependencyAppRequest",
    "UpsertFieldRestApiRequest",
    "UpsertFieldAddressRequest",
    "UpsertFieldDatabaseRequest",
    "UpsertFieldDateRequest",
    "UpsertFieldAIRequest",
    "UpsertFieldCodeRequest",
    "UpsertFieldCodeReaderRequest",
    "UpsertFieldEmailInputRequest",
    "UpsertFieldEmojiRequest",
    "UpsertFieldFileRequest",
    "UpsertFieldGpsLocationRequest",
    "UpsertFieldLiveTrackingRequest",
    "UpsertFieldManualAddressRequest",
    "UpsertFieldPhoneNumberRequest",
    "UpsertFieldProgressBarRequest",
    "UpsertFieldSignatureRequest",
    "UpsertFieldRangeRequest",
    "UpsertFieldCounterRequest",
    "UpsertFieldSliderRequest",
    "UpsertFieldTimeRequest",
    "UpsertFieldToggleRequest",
    "UpsertFieldValidationRequest",
    "UpsertFieldVideoViewerRequest",
    "UpsertFieldVoiceRequest",
    "UpsertFieldFormulaRequest",
    "UpsertFieldImageViewerRequest",
    "UpsertFieldRichTextEditorRequest",
    "UpsertFieldNfcReaderRequest",
    "UpsertFieldNumberInputRequest",
    "UpsertFieldPdfViewerRequest",
    "UpsertFieldReadOnlyFileRequest",
    "UpsertFieldReadOnlyTextRequest",
    "UpsertFieldTagsRequest",
    "UpsertFieldUniqueSequentialRequest",
    "UpsertFieldDropdownRequest",
    "UpsertFieldRadioRequest",
    "UpsertFieldUrlInputRequest",
    "UpsertFieldCheckboxRequest",
    "UpsertFieldRazorpayPaymentGatewayRequest",
    "UpsertFieldEazypayPaymentGatewayRequest",
    "UpsertFieldPaypalPaymentGatewayRequest",
    "UpsertFieldStripePaymentGatewayRequest",
    "UpsertFieldButtonRequest",

    # ===== Response Models =====
    "BaseResponse",
    "AppDefinitionResponse",
    "AppCreationResponse",
    "SubmissionResponse",
    "SubmissionsAggregationResponse",
    "SubmissionsResponse",
    "SubmissionsExcelResponse",
    "WorkflowResponse",
    "WorkflowStepResponse",
    "ChartResponse",
    "GetAppChartsResponse",
    "SubmissionsCountResponse",
    "WorkplaceUserResponse",
    "WorkplaceUserDetailsResponse",
    "WorkplaceUserAttributesResponse",
    "WorkplaceUserRoleResponse",
    "WorkplaceUserGroupsResponse",
    "AppUserResponse",
    "WorkplaceAppResponse",
    "WorkplaceUserAppsResponse",
    "WorkplaceUsersResponse",

    "FieldOperationResponse",
    "PageBreakOperationResponse",
    "UpsertSectionOperationResponse",
    "ReorderSectionOperationResponse",
]
