"""
Models for the Clappia API.
"""

from .definition import AppField, AppSection
from .workplace_user import WorkplaceUser
from .permissions import Permission
from .submission import (
    FilterCondition,
    SubmissionQuery,
    SubmissionQueryGroup,
    SubmissionFilters,
    AggregationOperand,
    AggregationDimension,
    AggregationMetric,
)
from .request import (
    GetAppDefinitionRequest,
    CreateAppRequest,
    AddFieldRequest,
    UpdateFieldRequest,
    GetSubmissionsRequest,
    GetSubmissionsAggregationRequest,
    CreateSubmissionRequest,
    EditSubmissionRequest,
    UpdateSubmissionStatusRequest,
    UpdateSubmissionOwnersRequest,
    GetSubmissionsInExcelRequest,
    GetSubmissionsCountRequest,
    GetWorkflowRequest,
    AddWorkflowStepRequest,
    RemoveWorkflowStepRequest,
    UpdateWorkflowStepRequest,
    ReorderWorkflowStepRequest,
    AddChartRequest,
    RemoveChartRequest,
    UpdateChartRequest,
    ReorderChartRequest,
    GetAppChartsRequest,
    AddUserToWorkplaceRequest,
    UpdateWorkplaceUserDetailsRequest,
    UpdateWorkplaceUserAttributesRequest,
    UpdateWorkplaceUserRoleRequest,
    UpdateWorkplaceUserGroupsRequest,
    AddUserToAppRequest,
    GetWorkplaceAppsRequest,
    GetWorkplaceUserAppsRequest,
    GetWorkplaceUsersRequest,
)
from .response import (
    AppDefinitionResponse,
    AppCreationResponse,
    SubmissionResponse,
    FieldOperationResponse,
    SubmissionsAggregationResponse,
    SubmissionsResponse,
    SubmissionsExcelResponse,
    WorkflowResponse,
    WorkflowStepResponse,
    ChartResponse,
    GetAppChartsResponse,
    SubmissionsCountResponse,
    WorkplaceUserResponse,
    WorkplaceUserDetailsResponse,
    WorkplaceUserAttributesResponse,
    WorkplaceUserRoleResponse,
    WorkplaceUserGroupsResponse,
    AppUserResponse,
    WorkplaceAppResponse,
    WorkplaceUserAppsResponse,
    WorkplaceUsersResponse,
)

__all__ = [
    # Definition Models
    "AppField",
    "AppSection",
    # Submission Models
    "FilterCondition",
    "SubmissionQuery",
    "SubmissionQueryGroup",
    "SubmissionFilters",
    "AggregationOperand",
    "AggregationDimension",
    "AggregationMetric",
    # Request Models
    "GetAppDefinitionRequest",
    "CreateAppRequest",
    "AddFieldRequest",
    "UpdateFieldRequest",
    "GetSubmissionsRequest",
    "GetSubmissionsAggregationRequest",
    "CreateSubmissionRequest",
    "EditSubmissionRequest",
    "UpdateSubmissionStatusRequest",
    "UpdateSubmissionOwnersRequest",
    "GetSubmissionsInExcelRequest",
    "GetSubmissionsCountRequest",
    "GetWorkflowRequest",
    "AddWorkflowStepRequest",
    "RemoveWorkflowStepRequest",
    "UpdateWorkflowStepRequest",
    "ReorderWorkflowStepRequest",
    "AddChartRequest",
    "RemoveChartRequest",
    "UpdateChartRequest",
    "ReorderChartRequest",
    "GetAppChartsRequest"
    "AddUserToWorkplaceRequest",
    "UpdateWorkplaceUserDetailsRequest",
    "UpdateWorkplaceUserAttributesRequest",
    "UpdateWorkplaceUserRoleRequest",
    "UpdateWorkplaceUserGroupsRequest",
    "AddUserToAppRequest",
    "GetWorkplaceAppsRequest",
    "GetWorkplaceUserAppsRequest",
    "GetWorkplaceUsersRequest",
    # Response Models
    "AppDefinitionResponse",
    "AppCreationResponse",
    "SubmissionResponse",
    "FieldOperationResponse",
    "SubmissionsAggregationResponse",
    "SubmissionsResponse",
    "SubmissionsExcelResponse",
    "WorkflowResponse",
    "WorkflowStepResponse",
    "ChartResponse",
    "GetAppChartsResponse",
    "SubmissionsCountResponse",
    "WorkplaceUserResponse",
    "WorkplaceUserDetailsResponse",
    "WorkplaceUserAttributesResponse",
    "WorkplaceUserRoleResponse",
    "WorkplaceUserGroupsResponse",
    "AppUserResponse",
    "WorkplaceAppResponse",
    "WorkplaceUserAppsResponse",
    "WorkplaceUsersResponse",
    "WorkplaceUser",
]
